version: '3'

services:

  discovery-service:
    container_name: discovery-service
    image: denpool/discovery-service
    restart: always
    ports:
      - "7777:8761"
    networks:
      - backend
    depends_on:
      zipkin:
        condition: service_healthy

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.1
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend
    depends_on:
      storage-service:
        condition: service_started

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - backend

  storage-service:
    container_name: storage-service
    image: denpool/storage-service:0.0.1
    restart: always
    ports:
      - "6500:6500"
    networks:
      - backend
    depends_on:
      discovery-service:
        condition: service_started


networks:
  backend:
volumes:
  db-data: